### ISSUE TITLE
get panic when iterator an empty trie

### ISSUE THREAD

**Issue by tcp9** [timtadh/data-structures#6]
Hi:
this is the case
``` go
package main

import (
	"github.com/timtadh/data-structures/trie"
)

func main() {
	t := trie.New()
	for _, _, next := t.Iterate()(); next != nil; _, _, next = next() {

	}
}
```

golang version: go version go1.11.4 linux/amd64
when i'm using go run, it occurs
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48ac3b]

goroutine 1 [running]:
github.com/timtadh/data-structures/trie.(*TST).Iterate.func1(0xc000067788, 0xc000090020, 0x0, 0x0, 0x0)
	/home/tcp9/go/src/github.com/timtadh/data-structures/trie/tst.go:215 +0x3b
main.main()
	/home/tcp9/go/src/test/test/main.go:9 +0x62
```

**Comment by timtadh** [comment]
Definitely looks like a bug. Will check it out.

**Comment by timtadh** [comment]
@tcp9 #7 should fix this for you. I am merging it.

**Comment by timtadh** [comment]
A release (https://github.com/timtadh/data-structures/releases/tag/v0.5.3) has been tagged. Please try updating to 0.5.3 (or master) and let me know if you are still having this problem.
